name: Build and deploy ASP.Net Core app to Azure Web App - kamksiteServer

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'  # Ensure this is the right .NET version

      - name: Build with dotnet
        run: dotnet build mksite.Server/mksite.Server.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish mksite.Server/mksite.Server.csproj -c Release -o ./myapp  # Publish to workspace

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./myapp  # Correct artifact path

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'kamksiteServer'
          slot-name: 'Production'
          package: ./  # Use current directory after artifact download
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C770C8FFF9C54089B98D579F299ED6D5 }}
